api:
    resource: "@ApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

home:
    type:     rest
    resource: ApiBundle\Controller\HomeController
products:
    type:     rest
    resource: ApiBundle\Controller\ProductController
stocks:
    type:     rest
    resource: ApiBundle\Controller\StockController
users:
    type:     rest
    resource: ApiBundle\Controller\UserController
auth-tokens:
    type:     rest
    resource: ApiBundle\Controller\AuthTokenController
access:
    type:     rest
    resource: ApiBundle\Controller\StockAccessController
history:
    type:     rest
    resource: ApiBundle\Controller\HistoryController