<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\History;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByStock($stock)
    {
        $qb = $this->createQueryBuilder('h')
            ->select('h, p, s')
            ->innerJoin('h.product', 'p')
            ->innerJoin('p.stock', 's')
            ->andWhere('p.stock = :stock')
            ->setParameter('stock', $stock)
            ->orderBy('h.date', 'DESC')
            ->getQuery();

        return $qb->execute();
    }
}
